[package]
name = "image-conv"
version = "0.1.0"
authors = ["Gaurav Patel <GauravPatel97@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
photon-rs = { git = "https://github.com/silvia-odwyer/photon"}
image = "0.23.13"
prettytable-rs = "^0.8"